// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpimwbsvwhubtuxgpryj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwaW13YnN2d2h1YnR1eGdwcnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5NTUyMDYsImV4cCI6MjA1MzUzMTIwNn0.IiWH9eOxEWlx7BS1XWObnK3X68lCGon1ncpDAF_0hM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);